### ISSUE TITLE
Won't launch: libpng12.so.0 missing

### ISSUE THREAD

**Issue by protist** [mahogny/glofacs#1]
I downloaded the stand-alone [Linux 64-bit binary](http://www.facsanadu.net/), but it won't launch.

```
$ ./facsanadu.sh
...
Loading library: 'libQtCore.so.4'...
 - already loaded, skipping...
Loading library: 'libcom_trolltech_qt_core.so'...
 - using deployment spec
 - ok!
Loading library: 'libQtGui.so.4'...
 - using deployment spec

	at com.trolltech.qt.internal.NativeLibraryManager.loadNativeLibrary(NativeLibraryManager.java:431)
	at com.trolltech.qt.internal.NativeLibraryManager.loadQtLibrary(NativeLibraryManager.java:356)
	at com.trolltech.qt.Utilities.loadQtLibrary(Utilities.java:145)
	at com.trolltech.qt.Utilities.loadQtLibrary(Utilities.java:141)
	at com.trolltech.qt.gui.QtJambi_LibraryInitializer.<clinit>(QtJambi_LibraryInitializer.java:7)
	... 1 more
Caused by: java.lang.UnsatisfiedLinkError: /tmp/QtJambi_protist_amd64_4.7.0_gcc-20100927-1542/lib/libQtGui.so.4: libpng12.so.0: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
	at java.lang.Runtime.load0(Runtime.java:810)
	at java.lang.Runtime.load(Runtime.java:798)
	at com.trolltech.qt.internal.NativeLibraryManager.loadLibrary_helper(NativeLibraryManager.java:458)
	at com.trolltech.qt.internal.NativeLibraryManager.loadNativeLibrary(NativeLibraryManager.java:426)
	... 5 more
```

I'm using an up-to-date Arch Linux system.

**Comment by protist** [comment]
Oh, I just needed to install my distro's [libpng12](https://archlinux.org/packages/community/x86_64/libpng12/). I misunderstood and thought everything was bundled in the app. Sorry for the noise!
